import type { Metadata } from 'next'
import Nav from '@/components/Nav'
import Footer from '@/components/Footer'

export const metadata: Metadata = {
  title: 'Privacy Policy - recall',
}

export default function Privacy() {
  return (
    <>
      <Nav />
      <main className="legal-wrap">
        <p className="legal-label">Legal</p>
        <h1>Privacy Policy</h1>
        <p className="legal-date">Effective date: May 2025</p>

        <p>
          Recall is a personal AI assistant desktop application. This policy describes what data
          we collect, how we use it, and your rights.
        </p>

        <h2>1. What we collect</h2>
        <ul>
          <li>
            <strong>Gmail data:</strong> We read email metadata and content via the Google Gmail
            API on your behalf. This data is fetched on-demand and is not stored on our servers.
            No email content is permanently retained by Recall.
          </li>
          <li>
            <strong>Google Calendar data:</strong> We read calendar events via the Google Calendar
            API to generate your morning brief. Calendar content is not stored server-side and is
            fetched fresh each time.
          </li>
          <li>
            <strong>Voice audio:</strong> When you use voice input, your audio is recorded locally
            in the Tauri desktop app, streamed to our backend for transcription, and then discarded.
            Voice recordings are processed in-memory only and are never stored.
          </li>
          <li>
            <strong>Recall items:</strong> Tasks, reminders, and notes you create are stored in our
            database (Supabase) associated with your account.
          </li>
          <li>
            <strong>Proactive job results:</strong> Summaries and brief metadata generated by our
            scheduled jobs are stored temporarily in our database to enable delivery to your device.
          </li>
        </ul>

        <h2>2. How we use your data</h2>
        <p>We use your data solely to provide Recall&apos;s features:</p>
        <ul>
          <li>Generating your daily morning brief (email summaries, calendar events, open tasks)</li>
          <li>Enabling voice-based task and reminder creation</li>
          <li>Delivering smart reminders and follow-up nudges</li>
          <li>Learning your usage patterns to improve relevance over time</li>
        </ul>
        <p>
          Your data is never sold, rented, or shared with third parties for advertising. It is never
          used to train AI models.
        </p>

        <h2>3. Third-party services</h2>
        <ul>
          <li>
            <strong>Google APIs (Gmail, Calendar):</strong> Data is fetched on-demand directly from
            Google&apos;s servers. Subject to{' '}
            <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">
              Google&apos;s Privacy Policy
            </a>
            .
          </li>
          <li>
            <strong>Anthropic API:</strong> Text is sent to Claude (Anthropic) for processing and
            generating responses. Subject to{' '}
            <a href="https://www.anthropic.com/privacy" target="_blank" rel="noopener noreferrer">
              Anthropic&apos;s Privacy Policy
            </a>
            .
          </li>
          <li>
            <strong>Supabase:</strong> Your recall items, session data, and proactive job results
            are stored in Supabase. Subject to{' '}
            <a href="https://supabase.com/privacy" target="_blank" rel="noopener noreferrer">
              Supabase&apos;s Privacy Policy
            </a>
            .
          </li>
          <li>
            <strong>Cartesia:</strong> Text is sent to Cartesia for voice synthesis. Subject to{' '}
            <a
              href="https://cartesia.ai/legal/privacy.html"
              target="_blank"
              rel="noopener noreferrer"
            >
              Cartesia&apos;s Privacy Policy
            </a>
            .
          </li>
        </ul>

        <h2>4. Data retention</h2>
        <ul>
          <li>
            <strong>Email and calendar content:</strong> Never stored on our servers. Fetched live
            per request from Google&apos;s APIs.
          </li>
          <li>
            <strong>Voice audio:</strong> Processed in-memory only. Discarded immediately after
            transcription. Not stored anywhere.
          </li>
          <li>
            <strong>Recall items (tasks, reminders, notes):</strong> Retained until you delete them
            or request account deletion.
          </li>
          <li>
            <strong>Proactive job results:</strong> Stored in our database. Deleted when your
            account is deleted.
          </li>
        </ul>

        <h2>5. Security</h2>
        <p>
          Your Google OAuth tokens are stored securely in our database and used only to fetch data
          on your behalf. We use HTTPS for all data transmission. Access is restricted to
          authenticated users only.
        </p>

        <h2>6. Your rights</h2>
        <p>
          You may request deletion of your account and all associated data at any time. To do so,
          email{' '}
          <a href="mailto:shivohamangal@gmail.com">shivohamangal@gmail.com</a> with the subject
          line &quot;Delete my account&quot;.
        </p>
        <p>
          You can revoke Recall&apos;s access to your Google account at any time by visiting{' '}
          <a
            href="https://myaccount.google.com/permissions"
            target="_blank"
            rel="noopener noreferrer"
          >
            Google Account Permissions
          </a>
          .
        </p>

        <h2>7. Changes to this policy</h2>
        <p>
          We may update this policy as the app evolves. Material changes will be announced via the
          GitHub repository. The effective date at the top of this page reflects the most recent
          revision.
        </p>

        <h2>8. Contact</h2>
        <p>
          Questions or concerns? Contact Shivoham Angal at{' '}
          <a href="mailto:shivohamangal@gmail.com">shivohamangal@gmail.com</a>.
        </p>
      </main>
      <Footer />
    </>
  )
}
