import type { Metadata } from 'next'
import Nav from '@/components/Nav'
import Footer from '@/components/Footer'

export const metadata: Metadata = {
  title: 'Privacy Policy - Recall',
}

export default function Privacy() {
  return (
    <>
      <Nav />
      <main className="legal-wrap">
        <p className="legal-label">Legal</p>
        <h1>Privacy Policy</h1>
        <p className="legal-date">Effective date: June 2026</p>

        <p>
          Recall is a personal AI assistant desktop application. This policy describes what data
          we collect, how we use it, and your rights.
        </p>

        <h2>1. What we collect</h2>
        <ul>
          <li>
            <strong>Gmail data:</strong> We read Gmail metadata and content via the Google Gmail
            API on your behalf. Recall may store a bounded preview of recent sent-email samples
            to personalize draft tone, and proactive job payloads may include email snippets that
            were surfaced to your app.
          </li>
          <li>
            <strong>Google Calendar data:</strong> We read calendar events via the Google Calendar
            API and can create calendar events when you ask Recall to do so. Proactive job payloads
            may include event details that were surfaced to your app.
          </li>
          <li>
            <strong>Google OAuth tokens:</strong> We store Google access and refresh tokens so
            Recall can provide Gmail and Calendar features while you are signed in.
          </li>
          <li>
            <strong>Voice audio:</strong> When you use voice input, your audio is recorded locally
            in the Tauri desktop app, sent to our transcription provider (Cartesia) to convert
            speech to text, and then discarded. Voice recordings are processed in-memory only and
            are never stored.
          </li>
          <li>
            <strong>Recall items:</strong> Tasks, reminders, and notes you create are stored in our
            database (Supabase) associated with your account.
          </li>
          <li>
            <strong>Proactive job results:</strong> Summaries, email cards, calendar cards, and
            brief metadata generated by scheduled jobs are stored in our database to enable delivery
            to your device.
          </li>
          <li>
            <strong>Personal memories:</strong> If you use the optional Memory feature, facts and
            preferences you ask Recall to remember are stored with our memory provider (Supermemory)
            to personalize responses. You can disable this feature.
          </li>
        </ul>

        <h2>2. How we use your data</h2>
        <p>We use your data solely to provide Recall&apos;s features:</p>
        <ul>
          <li>Generating your daily morning brief (email summaries, calendar events, open tasks)</li>
          <li>Creating Gmail drafts and Calendar events when you ask for them</li>
          <li>Enabling voice-based task and reminder creation</li>
          <li>Delivering smart reminders and follow-up nudges</li>
          <li>Personalizing draft style from recent sent-email samples</li>
          <li>Learning your usage patterns to improve relevance over time</li>
          <li>Remembering personal facts you ask Recall to save, to personalize responses (optional Memory feature)</li>
        </ul>
        <p>
          Your data is never sold, rented, or shared with third parties for advertising. It is never
          used to train AI models.
        </p>
        <p>
          Recall&apos;s use and transfer of information received from Google APIs adheres to the{' '}
          <a
            href="https://developers.google.com/terms/api-services-user-data-policy"
            target="_blank"
            rel="noopener noreferrer"
          >
            Google API Services User Data Policy
          </a>
          , including the Limited Use requirements.
        </p>

        <h2>3. Third-party services</h2>
        <ul>
          <li>
            <strong>Google APIs (Gmail, Calendar):</strong> Recall reads Gmail and Calendar data,
            saves Gmail drafts, and creates Calendar events on your behalf when requested. Subject
            to{' '}
            <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">
              Google&apos;s Privacy Policy
            </a>
            .
          </li>
          <li>
            <strong>Anthropic API:</strong> Text is sent to Claude (Anthropic) for processing and
            generating responses. Subject to{' '}
            <a href="https://www.anthropic.com/privacy" target="_blank" rel="noopener noreferrer">
              Anthropic&apos;s Privacy Policy
            </a>
            .
          </li>
          <li>
            <strong>OpenAI API:</strong> Text from Recall items is sent to OpenAI to generate
            embeddings for semantic search. Subject to{' '}
            <a href="https://openai.com/policies/privacy-policy" target="_blank" rel="noopener noreferrer">
              OpenAI&apos;s Privacy Policy
            </a>
            .
          </li>
          <li>
            <strong>Supabase:</strong> Your account data, Google OAuth tokens, Recall items,
            session data, email style profile, learned usage patterns, goals, suggestions, and
            proactive job results are stored in Supabase. Subject to{' '}
            <a href="https://supabase.com/privacy" target="_blank" rel="noopener noreferrer">
              Supabase&apos;s Privacy Policy
            </a>
            .
          </li>
          <li>
            <strong>Cartesia:</strong> When you use voice, audio is sent to Cartesia for
            transcription (speech-to-text) and response text is sent to Cartesia for voice synthesis
            (text-to-speech). Subject to{' '}
            <a
              href="https://cartesia.ai/legal/privacy.html"
              target="_blank"
              rel="noopener noreferrer"
            >
              Cartesia&apos;s Privacy Policy
            </a>
            .
          </li>
          <li>
            <strong>Supermemory:</strong> If the optional Memory feature is enabled, personal
            memories and profile data you save are stored with Supermemory to personalize Recall.
            Subject to{' '}
            <a href="https://supermemory.ai" target="_blank" rel="noopener noreferrer">
              Supermemory&apos;s Privacy Policy
            </a>
            .
          </li>
        </ul>

        <h2>4. Data retention</h2>
        <ul>
          <li>
            <strong>Google OAuth tokens:</strong> Retained while your Google account remains
            connected to Recall.
          </li>
          <li>
            <strong>Email style profile:</strong> A bounded encrypted cache of recent sent-email
            samples is retained while Google is connected and personalization is enabled. It is
            refreshed by overwriting the existing profile rather than accumulating historical
            versions.
          </li>
          <li>
            <strong>Proactive job results:</strong> Stored in our database to deliver morning
            briefs, email cards, calendar cards, and other proactive summaries to your device.
          </li>
          <li>
            <strong>Chat and session history:</strong> Stored so your conversations and context can
            continue across app sessions.
          </li>
          <li>
            <strong>Voice audio:</strong> Processed in-memory only. Discarded immediately after
            transcription. Not stored anywhere.
          </li>
          <li>
            <strong>Recall items (tasks, reminders, notes):</strong> Retained until you delete them
            or request account deletion.
          </li>
          <li>
            <strong>Personal memories:</strong> Retained with Supermemory until you delete them or
            disable the Memory feature.
          </li>
        </ul>

        <h2>5. Security</h2>
        <p>
          Your Google OAuth tokens and stored email style samples are encrypted at rest and are
          used only to provide Recall&apos;s features on your behalf. We use HTTPS for all data
          transmission. Access is restricted to authenticated users only, enforced by per-user
          row-level security.
        </p>

        <h2>6. Your rights</h2>
        <p>
          You may request deletion of your account and all associated data at any time. To do so,
          email{' '}
          <a href="mailto:shivohamangal@gmail.com">shivohamangal@gmail.com</a> with the subject
          line &quot;Delete my account&quot;.
        </p>
        <p>
          You can revoke Recall&apos;s access to your Google account at any time by visiting{' '}
          <a
            href="https://myaccount.google.com/permissions"
            target="_blank"
            rel="noopener noreferrer"
          >
            Google Account Permissions
          </a>
          .
        </p>

        <h2>7. Changes to this policy</h2>
        <p>
          We may update this policy as the app evolves. Material changes will be announced via the
          GitHub repository. The effective date at the top of this page reflects the most recent
          revision.
        </p>

        <h2>8. Contact</h2>
        <p>
          Questions or concerns? Contact Shivoham Angal at{' '}
          <a href="mailto:shivohamangal@gmail.com">shivohamangal@gmail.com</a>.
        </p>
      </main>
      <Footer />
    </>
  )
}
